# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0330d338489a801bc95de3e44238040034c7da9bb98f59a69c7aa8cdcd26ae0dc668b35729e36e4186b814bf4a391196bedf395ac552ed465dc7b9982f751d15

test:
  secret_key_base: c8b28754ee73251d4ab140d13eb7022e6da62a18b100e4cc2ddb294b76d345a21f85257a093af03ab0f4af2489555e6f52aadec7553324344f83ef6a0431a9b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
